CREATE TABLE OBT_COACH
(
ID_NO INT,
COACH_NAME VARCHAR(225),
MOBILE_NUMBER LONG,
EMAIL VARCHAR(225),
AGE INT,
DATE_OF_BIRTH DATE,
ADDRESS VARCHAR(225),
COACH_EXPIRENCE INT,
CURRENT_STUDENTS inT,
COACH_FEE DOUBLE

);

CREATE TABLE OBT_PRODUCT
(
PRODUCT_ID INT,
PRODUCT_NAME VARCHAR(225),
PRODUCT_MANUFACTURED_DATE DATE,
PRODUCT_EXPIRED_DATE DATE,
PRODUCT_USE_FOR VARCHAR(225),
PRODUCT_NET_WEIGHT VARCHAR(225),
PRODUCT_PRICE DOUBLE
);

CREATE TABLE PROMO(
PROGRAM_ID INT,
PROGRAM_NAME VARCHAR(225),
PROGRAM_DURATION VARCHAR(225),
PROGRAM_PRICE DOUBLE

);

CREATE TABLE OBT_USR_LOGIN
(
ID_NO INT,
USERNAME VARCHAR(225),
PASSWORD VARCHAR(225),
NEW_PASSWORD VARCHAR(225),
CREATED_BY VARCHAR(225),
CREATED_ON DATE,
MODIFY_BY VARCHAR(225),
MODIFY_ON DATE

);

SELECT * FROM obt_coach;
SELECT * FROM obt_promo;
SELECT * FROM obt_product;
SELECT * FROM obt_usr_login;
SELECT * FROM obt_usr_reg;